language: java
install: mvn -Dhttps.protocols=TLSv1.2 clean install
matrix:
 include:
  - jdk: oraclejdk8
    dist: trusty
  - jdk: oraclejdk7
    dist: precise
  - jdk: openjdk7
    dist: precise

# openjdk7 requires hostname see https://github.com/travis-ci/travis-ci/issues/5227
addons:
 hostname: canadensys-web-core.dev
